# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "CI"
  CI:
    # The type of runners that the job will run on
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-26.04,
            ubuntu-24.04,
            ubuntu-22.04,
            windows-2025-vs2026,
            windows-2025,
            windows-2022
          ]
        method: [local, network]
        rocm: [5.5.1]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v7.0.1

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

      - name: Run the action on this runner with method ${{matrix.method}}
        id: test-action
        uses: ./
        with:
          rocm: ${{ matrix.rocm }}
          method: ${{matrix.method}}
          log-file-suffix: '${{matrix.method}}-${{matrix.os}}'

      - name: Run the action on this runner with hip-sdk and rocblas subpackages
          (Linux)
        if: runner.os == 'Linux' && matrix.method == 'network'
        uses: ./
        with:
          method: ${{matrix.method}}
          sub-packages: '["hip-sdk"]'
          non-rocm-sub-packages: '["rocblas"]'
          log-file-suffix: 'hip-sdk-rocblas-${{matrix.method}}-${{matrix.os}}'

      - name: Print output rocm version
        run: echo "${{ steps.test-action.outputs.rocm }}"

      - name: Print output paths
        run: |
          echo "ROCM_PATH: ${{ steps.test-action.outputs.ROCM_PATH }}"
          echo "HIP_PATH: ${{ steps.test-action.outputs.HIP_PATH }}"

      - name: Test if hipcc is available
        run: hipcc --version

      - name: List paths (windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          ls $env:HIP_PATH
          ls $env:HIP_PATH\bin
          ls $env:HIP_PATH\include

      - name: List paths (linux)
        if: runner.os == 'Linux'
        run: |
          ls $ROCM_PATH
          ls $ROCM_PATH/bin
          ls $ROCM_PATH/include
